### PR TITLE
pull dev to the current branch

### PR DESCRIPTION
**Pull request by XPC1995**

### CODE REVIEW

**Comment by Whatsoutside** [comment]
What is going on here? You can just merge the dev into your own branch, dont make a PR for that

**Comment by XPC1995** [comment]
Yes, I just created this second branch because the build always failed in my previous branch. I will merge the dev into my first branch

**Comment by Whatsoutside** [comment]
but your build fails because your code causes it to fail. The dev is fine,  even without the merge it should be able to run

**Comment by XPC1995** [comment]
Sorry for the delayed reply. I can send you a screenshot. The mapImporterTest keeps throwing the error, but I didn't change anything in the MapImport or the mapImporterTest part. Also, my code didn't have any connection with the dev branch. I have no idea where this error is from

**Pull request closed without merging**
